@startuml
'https://plantuml.com/sequence-diagram
autonumber 10 10 "<b>[000]"
autonumber stop

actor master
participant communication_master            as com
participant control_linearActuator          as LA
participant communication_linearActuator    as nanoRX
actor       Nanos                           as nanos


com -> com : Wait command
master -> com : Send command
master <-- com : Check Reception

nanos ->o nanoRX : Send position of LinearActuator
destroy nanoRX
note left
Si rien n'est reçu depuis 'timeOut'
end note
autonumber resume "<font color=red><b>Emergency  "
nanoRX -> LA : Rise
autonumber stop

com <- LA : Emergency
master <- com : Emergency

@enduml