@startuml
'https://plantuml.com/sequence-diagram
actor master
participant communication_master            as com
participant control_linearActuator          as LA
participant communication_linearActuator    as nanoRX
actor       Nanos                           as nanos


com -> com : Wait command
master -> com : Send command

nanos -> nanoRX : Send position of LinearActuator
note left
Dès qu'une information arrive
elle est mise à jour dans le LinearActuator
end note
activate nanoRX

nanoRX -> LA : Update position of LinearActuator
deactivate nanoRX

master <-- com : Check Reception

com -> LA   : Execute commande (LinearActuator)

master <-- com : End of execution



@enduml