@startuml
'https://plantuml.com/sequence-diagram
participant CommunicationController         as com
participant LinearActuatorControl           as LA
participant CommunicationLinearActuator     as nano


com -> LA   : execute commande
com <- nano : send mesure | emergency | debug

nano -> LA : Emergency



@enduml