@startuml
'https://plantuml.com/object-diagram
left to right direction
' Horizontal lines: -->, <--, <-->
' Vertical lines: ->, <-, <->

package "LinearActuator" <<folder>>{
object baseLegA {
     Constantes : Id, trigMin, trigMax
     Pins = pwm, dir1, dir2
     Reception Nanos  : positionInt, positionMm
     Order Master : target, error
}
object middleLegA{
  Constantes : Id, trigMin, trigMax
  Pins = pwm, dir1, dir2
  Reception Nanos  : positionInt, positionMm
  Order Master : target, error
}
object endLegA{
   Constantes : Id, trigMin, trigMax
   Pins = pwm, dir1, dir2
   Reception Nanos  : positionInt, positionMm
   Order Master : target, error
}
object baseLegB{
    Constantes : Id, trigMin, trigMax
    Pins = pwm, dir1, dir2
    Reception Nanos  : positionInt, positionMm
    Order Master : target, error
}
object middleLegB{
  Constantes : Id, trigMin, trigMax
  Pins = pwm, dir1, dir2
  Reception Nanos  : positionInt, positionMm
  Order Master : target, error
}
object endLegB{
   Constantes : Id, trigMin, trigMax
   Pins = pwm, dir1, dir2
   Reception Nanos  : positionInt, positionMm
   Order Master : target, error
}
}

object LegA {
    LinearActuator_t : baseLeg, middleLeg, endLeg
}
object LegB{
   LinearActuator : baseLeg, middleLeg, endLeg
}

object MasterCommunication {
}
object MuxCommunication



baseLegA   -> LegA
middleLegA -> LegA
endLegA    -> LegA

baseLegB   -> LegB
middleLegB -> LegB
endLegB    -> LegB



@enduml
